version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: ci
          command: npm run ci
      - run:
          name: codecov
          command: 'npm i codecov && npx codecov'
      - store_artifacts:
          path: coverage/lcov-report
          destination: test
